services:
  OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapter
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDao
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopModuleSettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopModuleSettingDao
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Service\ShopSettingEncoderInterface:
    class: OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Service\ShopSettingEncoder
    public: false