services:
  OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapter
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\ContentFactory:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\ContentFactory

# TemplateLogic
  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\InputHelpLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\InputHelpLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SeoUrlLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SeoUrlLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AddUrlParametersLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AddUrlParametersLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AssignAdvancedLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AssignAdvancedLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IncludeDynamicLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IncludeDynamicLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IfContentLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IfContentLogic
