services:
  OxidEsales\Eshop\Core\Config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', getConfig]
    public: false

  OxidEsales\Eshop\Core\UtilsView:
    class: OxidEsales\Eshop\Core\UtilsView
    factory: ['OxidEsales\Eshop\Core\Registry', getUtilsView]
    public: false

  OxidEsales\EshopCommunity\Internal\Twig\TwigContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Twig\TwigContext
    autowire: true
    public: true

  OxidEsales\EshopCommunity\Internal\Twig\TemplateEngineConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Twig\TwigEngineConfiguration
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Twig\TwigContextInterface'
    public: true

  Symfony\Component\Templating\TemplateNameParserInterface:
    class: Symfony\Component\Templating\TemplateNameParser
    public: false

  twig:
    class: Twig\Environment
    arguments:
      - '@twig.loader'
      - "@=service('OxidEsales\\\\EshopCommunity\\\\Internal\\\\Twig\\\\TemplateEngineConfigurationInterface').getParameters()"
    public: false
      - [addExtension, ['@OxidEsales\EshopCommunity\Internal\Twig\Extensions\InputhelpExtension']]

  OxidEsales\EshopCommunity\Internal\Twig\TwigEngine:
    class: OxidEsales\EshopCommunity\Internal\Twig\TwigEngine
    arguments:
      - '@twig'
      - '@Symfony\Component\Templating\TemplateNameParserInterface'
    public: false

  OxidEsales\EshopCommunity\Internal\Twig\TemplateLoaderNameParser:
    class: OxidEsales\EshopCommunity\Internal\Twig\TemplateLoaderNameParser
    public: false

  # Loaders

  twig.loader.filesystem:
    class: Twig\Loader\FilesystemLoader
    arguments: ["@=service('OxidEsales\\\\EshopCommunity\\\\Internal\\\\Twig\\\\TwigContextInterface').getTemplateDirectories()"]
    tags: ['twig.loader']

  OxidEsales\EshopCommunity\Internal\Twig\Loader\ContentTemplateLoader:
    class: OxidEsales\EshopCommunity\Internal\Twig\Loader\ContentTemplateLoader
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Twig\TemplateLoaderNameParser'
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\ContentFactory'
    tags: ['twig.loader']

  twig.loader.chain:
    class: Twig\Loader\ChainLoader
    public: false

  # Extensions

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\MathExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\MathExtension
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\IncludeExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\IncludeExtension
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IncludeDynamicLogic'
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\SmartyExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\SmartyExtension
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\MailtoExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\MailtoExtension
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\UrlExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\UrlExtension
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SeoUrlLogic'
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AddUrlParametersLogic'
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\AssignAdvancedExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\AssignAdvancedExtension
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AssignAdvancedLogic'
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\InputHelpExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\InputHelpExtension
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\InputHelpLogic'
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\HasRightsExtension\HasRightsParser:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\HasRightsExtension\HasRightsParser
    tags: ['twig.parser']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\HasRightsExtension\HasRightsExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\HasRightsExtension\HasRightsExtension
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\IfContentExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\IfContentExtension
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IfContentLogic'
    tags: ['twig.extension']
