services:
  OxidEsales\EshopCommunity\Internal\Templating\EngineInterface:
    class: OxidEsales\EshopCommunity\Internal\Templating\DelegatingEngine
    arguments:
      - ['@OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine', '@OxidEsales\EshopCommunity\Internal\Twig\TwigEngine']
    calls:
      - method: addFallBackEngine
        arguments:
          - '@OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine'
    public: true
    tags: ['templating']