services:
  OxidEsales\EshopCommunity\Internal\Templating\TemplateEngineBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Templating\TemplateEngineBridge
    arguments:
      - ['@OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine']
    calls:
      - method: addFallBackEngine
        arguments:
          - '@OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine'
    public: true
    tags: ['templating']