services:

  OxidEsales\EshopCommunity\Internal\Module\ShopModuleSetting\ShopModuleSettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\ShopModuleSetting\ShopModuleSettingDao
    autowire: true
    public: false