services:
  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationService
    autowire: true
    calls:
      - [addHandler, ['@oxid_esales.module.setup.path_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.version_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.templates_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.controllers_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.class_extensions_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.template_blocks_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.shop_module_setting_module_setting_handler']]
      - [addValidator, ['@oxid_esales.module.setup.validator.controllers_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.class_extensions_module_setting_validator']]

  oxid_esales.module.setup.version_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::VERSION
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_VERSIONS
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.path_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::PATH
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_PATHS
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.templates_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::TEMPLATES
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_TEMPLATES
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.controllers_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::CONTROLLERS
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_CONTROLLERS
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::SMARTY_PLUGIN_DIRECTORIES
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_SMARTY_PLUGIN_DIRECTORIES
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.class_extensions_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ClassExtensionsModuleSettingHandler
    autowire: true

  oxid_esales.module.setup.template_blocks_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\TemplateBlockModuleSettingHandler
    autowire: true

  oxid_esales.module.setup.shop_module_setting_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopModuleSettingModuleSettingHandler
    autowire: true

  oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\SmartyPluginDirectoriesModuleSettingValidator
    autowire: true

  oxid_esales.module.setup.validator.controllers_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\ControllersModuleSettingValidator
    autowire: true

  oxid_esales.module.setup.validator.class_extensions_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\ClassExtensionsModuleSettingValidator
    autowire: true