services:
  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationService
    autowire: true
    calls:
      - [addHandler, ['@oxid_esales.module.setup.path_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.version_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.templates_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.controllers_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler']]
      - [addValidator, ['@oxid_esales.module.setup.validator.controllers_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator']]

  oxid_esales.module.setup.version_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - version
      - aModuleVersions
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.path_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - path
      - aModulePaths
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.templates_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - templates
      - aModuleTemplates
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.controllers_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - controllers
      - aModuleControllers
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - smartyPluginDirectories
      - moduleSmartyPluginDirectories
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'


  oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\ControllersModuleSettingValidator

  oxid_esales.module.setup.validator.controllers_module_setting_validator:
      class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\SmartyPluginDirectoriesModuleSettingValidator