parameters:
  module_configuration_path: OxidEsales\EshopCommunity\Internal\Configuration\Module
  oxid_esales.configuration.module.metadata_settings:
    v2.0:
      - blocks
      - controllers
    v2.1:
      - blocks
      - controllers
      - smartyDirectories

services:
  OxidEsales\EshopCommunity\Internal\Configuration\Module\Service\ModuleActivationServiceInterface:
    class: %module_configuration_path%\Service\ModuleActivationService
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Configuration\Module\Service\ModuleDataTransferServiceInterface:
    class: %module_configuration_path%\Service\ModuleDataToShopConfigurationTransferService
    arguments:
      - '@oxid_esales.configuration.module.data_mapper.module_configuration_to_shop_configuration_data_mapper'
      - '@OxidEsales\EshopCommunity\Internal\Common\Configuration\ShopConfigurationSettingDaoInterface'
    public: false

  oxid_esales.configuration.module.data_mapper.module_configuration_to_shop_configuration_data_mapper:
    class: %module_configuration_path%\DataMapper\ModuleConfigurationToShopConfigurationDataMapper
    public: false

  OxidEsales\EshopCommunity\Internal\Configuration\Module\Dao\ProjectConfigurationDaoInterface:
    class: %module_configuration_path%\Dao\ProjectConfigurationDao
    arguments:
      - '@oxid_esales.configuration.module.project_configuration_yaml_file_storage'
      - '@OxidEsales\EshopCommunity\Internal\Configuration\Module\DataMapper\ProjectConfigurationDataMapperInterface'
    public: false

  oxid_esales.configuration.module.project_configuration_yaml_file_storage:
    class: OxidEsales\EshopCommunity\Internal\Common\Storage\YamlFileStorage
    arguments:
      - '@oxid_esales.configuration.module.project_configuration_yaml_file_locator'
      - '/tmp/configuration.yaml'
    public: false

  oxid_esales.configuration.module.project_configuration_yaml_file_locator:
    class: Symfony\Component\Config\FileLocator
    public: false

  OxidEsales\EshopCommunity\Internal\Configuration\Module\DataMapper\ProjectConfigurationDataMapperInterface:
    class: %module_configuration_path%\DataMapper\ProjectConfigurationDataMapper
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Configuration\Module\DataMapper\ShopConfigurationDataMapperInterface'
    public: false

  OxidEsales\EshopCommunity\Internal\Configuration\Module\DataMapper\ShopConfigurationDataMapperInterface:
    class: %module_configuration_path%\DataMapper\ShopConfigurationDataMapper
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Configuration\Module\DataMapper\ModuleConfigurationDataMapperInterface'
    public: false

  OxidEsales\EshopCommunity\Internal\Configuration\Module\DataMapper\ModuleConfigurationDataMapperInterface:
    class: %module_configuration_path%\DataMapper\ModuleConfigurationDataMapper
    arguments:
      - '@oxid_esales.configuration.module.data_mapper.validator.metadata_setting_validator'
    public: false

  oxid_esales.configuration.module.data_mapper.validator.metadata_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Configuration\Module\Validator\MetadataSettingValidator
    arguments:
      - '%oxid_esales.configuration.module.metadata_settings%'
    public: false