parameters:
  oxid_esales.module.configuration.metadata_schemata:
    '2.0':
      0: id
      1: version
      2: title
      3: description
      4: lang
      5: thumbnail
      6: author
      7: url
      8: email
      9: extend
      10: controllers
      11: templates
      blocks: [theme, template, block, file, position]
      settings: [group, name, type, value, constraints, position]
      12: events
    '2.1':
      0: id
      1: version
      2: title
      3: description
      4: lang
      5: thumbnail
      6: author
      7: url
      8: email
      9: extend
      10: controllers
      11: templates
      blocks: [theme, template, block, file, position]
      settings: [group, name, type, value, constraints, position]
      12: events
      13: smartyPluginDirectories

services:
  oxid_esales.module.metadata.metadatadatamapper:
    class: OxidEsales\EshopCommunity\Internal\Module\MetaData\MetaDataDataMapper
    public: false
    autowire: true

  OxidEsales\EshopCommunity\Internal\Module\MetaData\Validator\MetaDataValidatorInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\MetaData\Validator\MetaDataValidator
    public: false
    autowire: true

  OxidEsales\EshopCommunity\Internal\Module\MetaData\MetaDataSchemataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\MetaData\MetaDataSchemataProvider
    arguments:
      - '%oxid_esales.module.configuration.metadata_schemata%'
    public: false

  OxidEsales\EshopCommunity\Internal\Module\MetaData\MetaDataNormalizerInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\MetaData\MetaDataNormalizer
    public: false

  oxid_esales.module.metadata.metadatadataprovider:
    class: OxidEsales\EshopCommunity\Internal\Module\MetaData\MetaDataDataProvider
    autowire: true
    public: false
